name: Docker build and release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
      version_short: ${{ steps.version.outputs.version_short }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get version
        id: version
        run: | 
          VERSION=$(cat version.txt)
          echo "Current version: $VERSION"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          echo "version_short=$(echo $VERSION | cut -d. -f1,2)" >> "$GITHUB_OUTPUT"

  docker:
    name: Docker build and release
    uses: the0mikkel/ci/.github/workflows/docker.yml@v1.1.4
    permissions:
      contents: read
      packages: write
    needs: version
    with:
      tags: >-
        ${{ needs.version.outputs.version_short }}
        ${{ needs.version.outputs.version }}
        ${{ needs.version.outputs.version }}-apache
        type=raw,value=latest,enable={{is_default_branch}}
