name: Docker build and release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get version
        id: version
        run: | 
          VERSION=$(cat version.txt)
          echo "Current version: $VERSION"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

  docker:
    name: Docker build and release
    uses: the0mikkel/ci/.github/workflows/docker.yml@v1.1.4
    permissions:
      contents: read
      packages: write
    needs: version
    with:
      semver: ${{ needs.version.outputs.version }}
